%  Copyright 2024 California Institute of Technology
%
%  Licensed under the Apache License, Version 2.0 (the "License");
%  you may not use this file except in compliance with the License.
%  You may obtain a copy of the License at
%
%      http://www.apache.org/licenses/LICENSE-2.0
%
%  Unless required by applicable law or agreed to in writing, software
%  distributed under the License is distributed on an "AS IS" BASIS,
%  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
%  See the License for the specific language governing permissions and
%  limitations under the License.

function make_correlation_visualizations(output_path_prefix)
% make_correlation_visualizations    Visualize the displacement maps generated by landmark_comparison

% These MatlabExchange packages must be in the Matlab userpath
addpath([userpath '/colorbrewer']);
addpath([userpath '/cbarrow_v1.1/cbarrow/']);

coor_files = dir(output_path_prefix + "*.tif");
for f=coor_files'
    filepath = [f.folder '/' f.name];
    output_prefix = replace(filepath, '.tif', '');
    if(contains(filepath, 'delta_x_'))
        title = "Delta X";
        limit = [-50, 50];
    elseif(contains(filepath, 'delta_y_'))
        title = "Delta Y";
        limit = [-50, 50];  
    elseif(contains(filepath, 'delta_z_'))
        title = "Delta Z";
        limit = [-20, 20];
    else
        continue;
    end 
    I = imread(filepath);
    mask = I==0;
    visualize_corr(I, output_prefix, title, limit, mask);
end

disp("All figures have been generated.")

close all;
clear;

end